# Generated by Django 4.2.1 on 2024-04-23 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0), null=True),
        ),
    ]
