# Generated by Django 4.2.1 on 2024-06-29 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0002_alter_user_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
